P1:
  hostname: "192.168.2.5"      
  port: 5002                 # Cập nhật số port thực tế của P1 trên GNS3
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

P2:
  hostname: "192.168.2.5"
  port: 5003                 # Cập nhật số port thực tế của P2
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

PE1:
  hostname: "192.168.2.5"
  port: 5005                 # Cập nhật số port thực tế của PE1
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

PE2:
  hostname: "192.168.2.5"
  port: 5004                 # Cập nhật số port thực tế của PE2
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

# P1:
#   hostname: "172.20.10.3"      
#   port: 5002                 # Cập nhật số port thực tế của P1 trên GNS3
#   device_type: "cisco_ios_telnet"
#   username: "admin"
#   password: "123456"

# P2:
#   hostname: "172.20.10.3"
#   port: 5003                 # Cập nhật số port thực tế của P2
#   device_type: "cisco_ios_telnet"
#   username: "admin"
#   password: "123456"

# PE1:
#   hostname: "172.20.10.3"
#   port: 5005                 # Cập nhật số port thực tế của PE1
#   device_type: "cisco_ios_telnet"
#   username: "admin"
#   password: "123456"

# PE2:
#   hostname: "172.20.10.3"
#   port: 5004                 # Cập nhật số port thực tế của PE2
#   device_type: "cisco_ios_telnet"
#   username: "admin"
#   password: "123456"
