# Cấu hình thiết bị mạng
default:
  hostname: "192.168.116.170"
  device_type: "cisco_ios"
  username: "admin"
  password: "123456"
  secret: "123456"
  port: 22
  conn_timeout: 60
  auth_timeout: 60
  global_delay_factor: 2