P1:
  hostname: "127.0.0.1"      
  port: 5000                 # Cập nhật số port thực tế của P1
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

P2:
  hostname: "127.0.0.1"
  port: 5001                 # Cập nhật số port thực tế của P2
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

PE1:
  hostname: "127.0.0.1"
  port: 5002                 # Cập nhật số port thực tế của PE1
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

PE2:
  hostname: "127.0.0.1"
  port: 5003                 # Cập nhật số port thực tế của PE2
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

CE-1A:
  hostname: "127.0.0.1"
  port: 5004                 # Cập nhật số port thực tế của CE-1A
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

CE-1B:
  hostname: "127.0.0.1"
  port: 5005                 # Cập nhật số port thực tế của CE-1B
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

CE-2A:
  hostname: "127.0.0.1"
  port: 5006                 # Cập nhật số port thực tế của CE-2A
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

CE-2B:
  hostname: "127.0.0.1"
  port: 5007                 # Cập nhật số port thực tế của CE-2B
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

Switch1:
  hostname: "127.0.0.1"
  port: 5008                 # Cập nhật số port thực tế của Switch 1
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

Switch2:
  hostname: "127.0.0.1"
  port: 5009                 # Cập nhật số port thực tế của Switch 2
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"

Switch3:
  hostname: "127.0.0.1"
  port: 5010                 # Cập nhật số port thực tế của Switch 3
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"  

Switch4:
  hostname: "127.0.0.1"
  port: 5011                 # Cập nhật số port thực tế của Switch 4
  device_type: "cisco_ios_telnet"
  username: "admin"
  password: "123456"  